dist: trusty
sudo: required
language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo chmod +x .travis/build.sh
  - sudo chmod +x bin/common.sh
  - sudo chmod +x bin/debug.sh
script:
  - .travis/build.sh
